### ISSUE TITLE
Only one worker node is started

### ISSUE THREAD

**Issue by eli-jordan** [mesos/storm#100]
Not sure if this is the right place to ask this question, but I didn't find a mailing list specific to this project.

I have the mesos-storm framework running via marathon as per the instructions in the readme. I am able to run topologies successfully. However, it seems that only one storm worker (aka mesos task). I was expecting this to be controlled by the config when submitting the topology. e.g. I would have expected the following to launch 4 worker nodes.

```scala
val topology = ...
val conf = new Config()
conf.setDebug(true)
conf.setNumWorkers(4)
StormSubmitter.submitTopologyWithProgressBar("word-counter-drpc", conf, topology.build())
```

Is there some other configuration needed to launch multiple workers?

**Comment by erikdw** [comment]
(Opening an issue seems the only way to ask such Qs, we don't have a mailing list for this project.)

Regarding the actual question:  the number of workers is setting the number of desired worker *processes* for your topology (it's not setting the number of "nodes").  And those worker processes correspond to Mesos Tasks as you pointed out. 

So if you have less worker processes than expected, I'd compare the resource demands of your topology as compared to what your cluster has available.

1. How much CPU & memory per topology worker have you configured?  Since I don't see it explicitly set, it's defaulting to 1 CPU & 1000MB of RAM per worker.  But that doesn't account for the Mesos Executor (MesosSupervisor) overhead, which is 0.1 CPU & 500MB of RAM by default.  How many MesosSupervisors you have depends on how many hosts the work gets spread out on.
  * Defaults: https://github.com/mesos/storm/blob/9bd5a3ec00e9e1f3953e14ba3174b3184b36b0da/storm/src/main/storm/mesos/MesosCommon.java#L40-L43
2. How many "worker" hosts do you have?  (The hosts running `mesos-slave`.)  How much CPU and memory is being offered up by mesos from those hosts?

For example, let's say you had 2 worker hosts, each with 3 cores and 4000MB offer-able RAM, and you left all the resource limits as their defaults.  Then the MesosNimbus (the Mesos Scheduler for this framework) would try to schedule 2 workers onto each host, leading to:
* 1000MB*2 & 1core*2 (worker) + 500MB & 0.1core (MesosSupervisor) == 2500MB & 2.1 cores, per host.

I'm guessing you don't have enough worker hosts or worker host resources to run 4 worker processes with the default resource limits.

**Comment by eli-jordan** [comment]
@erikdw Thanks for the helpful answer. Your guess was correct. I added

```scala
 conf.put("topology.mesos.worker.cpu", new java.lang.Double(0.1))
 conf.put("topology.mesos.worker.mem.mb", new java.lang.Integer(512))
```

and saw four mesos tasks started when the topology was deployed.

On a vaguely related note. I ran into this when going through the storm trident tutorial, and noticed that the DRPC server is not started by the `run-with-marathon.sh` script. What would be the recommended way to launch the drpc server?

**Comment by erikdw** [comment]
@eli-jordan : glad it helped.  Can you please give me a pointer to the "storm trident tutorial" (I wanna see how it led to here)?

Launching the DRPC server with marathon seems like a good idea.  I haven't learned about what *this* project is doing with Marathon yet...

BTW, if you know how to use DRPC in storm, you might feel like helping a persistent user on the storm-users list that keeps asking questions about DRPC.  User email: `prog.researcher@gmail.com`.

**Comment by eli-jordan** [comment]
Its just the tutorial on the storm website at [trident tutorial](http://storm.apache.org/documentation/Trident-tutorial.html)

I didn't really lead here, it just about using trident, and uses DRPC. I just happen to be testing my code on a storm-mesos cluster.

**Comment by erikdw** [comment]
@eli-jordan : ah, well, you probably already know more than me, and definitely more than the person asking a million questions. :) The storm-drpc docs are *really* unclear about how to operate in a normal cluster outside of a "storm-in-a-box" type of cluster where you run everything inside the process (LocalCluster).

**Comment by erikdw** [comment]
Closing this issue since I think the main Q is already answered.
