### ISSUE TITLE
remove examples from release packages

### ISSUE THREAD

**Issue by erikdw** [mesos/storm#178]
The storm releases have increased in size by 8+ times from 0.9.7 to 1.0.2.  Part of that growth is from the `examples/` directory in the binary release being way larger, so we can mitigate the problem by removing that directory when bundling the package up in `bin/build-release.sh`.

**Comment by dinoba** [comment]
@erikdw 

can you update doc please. 

Example topology should be run like this

./bin/storm jar -c nimbus.host=192.168.1.39 -c nimbus.thrift.port=3681 examples/storm-starter/storm-starter-topologies-1.0.2.jar **org.apache.storm.starter.WordCountTopology** word-count

instead of

storm.starter.WordCountTopology

**Comment by erikdw** [comment]
@dinoba : feel free to send a PR.  I'm super busy.

**Comment by erikdw** [comment]
And.... now I see that you did open a PR: #178 is the PR.

**Comment by erikdw** [comment]
Thanks @fuji-151a for fixing this!
