### ISSUE TITLE
Shutdown cluster via storm UI

### ISSUE THREAD

**Issue by pdread100** [mesos/storm#46]
It would be nice if there were options to shutdown the cluster from the Storm UI.

**Comment by echinthaka** [comment]
I think this is a tricky request since storm UI is maintained by storm project and that doesn't have any knowledge about the storm/mesos integration.

**Comment by erikdw** [comment]
@echinthaka : depends on what "cluster" means in @pdread100's request.  If it means the Storm cluster then that seems more possible.  But if it means Mesos cluster then that is beyond the scope of the Storm UI.

**Comment by echinthaka** [comment]
@erikdw assuming cluster means storm cluster, are you suggesting this project should improve the storm UI to enable that shutdown (via some kind of option)?

**Comment by erikdw** [comment]
Nah, just suggesting it's possible if Storm provides a "kill all topologies" button, which would cause all the Worker processes to die.  That would cause all the [Supervisors to kill themselves](https://github.com/mesos/storm/blob/c13c13311b38e97ff0dba95c982461d18508700a/src/storm/mesos/MesosSupervisor.java#L217-L220), since no topologies' workers would be assigned for sometime.  Thus turning off the Storm Supervisors and Workers, and effectively shutting off the Storm cluster.  So it's something that *can* be done, just not as part of this project.  So I'd say we should file a ticket against Storm (or find an existing one) and close this issue with a pointer to that ticket.

**Comment by erikdw** [comment]
Filed a bug in the Storm project to add such a button:
* https://issues.apache.org/jira/browse/STORM-1216
