### ISSUE TITLE
storm-mesos 0.9.3 download location

### ISSUE THREAD

**Issue by echinthaka** [mesos/storm#52]
Seems like `http://downloads.mesosphere.io/storm/storm-mesos-0.9.3.tgz` is still not available. Do we know when its gonna be available? In the mean while I created my own release and uploaded to a local location. But like to get it from mesosphere location.

**Comment by erikdw** [comment]
@echinthaka : I'm assuming you're referencing the [`mesos.executor.uri` in the storm.yaml](https://github.com/mesos/storm/blob/3666d140029a5834c8410b3918d34b2c03343884/storm.yaml#L25-L27), which controls downloading of the mesos executor binary bits every time a MesosSupervisor is launched on a mesos-slave host.

I think we should probably remove that as a default configuration for a few reasons:
1. having tons of mesos servers all over the world hitting the mesosphere website for these big Jars is probably unfriendly
2. having an external dependency for runtime infrastructure processes seems unwise
3. if you make any changes to the 
4. (as you've noted) it's hard to rely upon the mesosphere downloads being updated all the time.  Perhaps hosting it within github would a bit easier since anyone with push perms could update it...

Perhaps it's better for the default config to (ab)use the [HTTP file server that MesosNimbus already launches](https://github.com/mesos/storm/blob/3666d140029a5834c8410b3918d34b2c03343884/src/storm/mesos/MesosNimbus.java#L145-L149)?

Or maybe I'm misunderstanding and you just want an already built version of storm-mesos?  If so then we can use my idea of storing the builds in github above.

**Comment by echinthaka** [comment]
thanks @erikdw . I was referring for an already built version hosted in mesosphere. I prefer that over a version we build on our own coz the code in github could change without somebody changing the version in pom.xml. Also, it will be uniform.

**Comment by erikdw** [comment]
Ok, cool.  Yeah, I think we can have some "core committee" build it and put it on github.   I'll talk to @tnachen about this next week at mesoscon.

**Comment by erikdw** [comment]
This issue is already discussed in https://github.com/mesos/storm/issues/18, I'm closing this issue since it's a duplicate.   As mentioned in that other issue, we need to come up with a verison/naming scheme, but that's not super hard.  And the binaries will be served from github proper.
