### ISSUE TITLE
Issues with getting storm-mesos 0.9.3 to work

### ISSUE THREAD

**Issue by echinthaka** [mesos/storm#55]
I ran `bin/build-release.sh` to build the latest release, deployed the release and was trying to run it. When I ran `bin/storm-mesos nimbus` it fails silently. Hence, I ran `sh bin/storm nimbus storm.mesos.MesosNimbus` and it fails with the following error. Really appreciate if someone can help me to fix this.

```
$ sh bin/storm nimbus storm.mesos.MesosNimbus
bin/storm: 19: bin/storm: import: not found
bin/storm: 20: bin/storm: import: not found
bin/storm: 21: bin/storm: import: not found
bin/storm: 22: bin/storm: import: not found
bin/storm: 23: bin/storm: import: not found
bin/storm: 24: bin/storm: import: not found
bin/storm: 25: bin/storm: try:: not found
bin/storm: 27: bin/storm: from: not found
bin/storm: 28: bin/storm: except: not found
bin/storm: 30: bin/storm: from: not found
bin/storm: 31: bin/storm: try:: not found
bin/storm: 33: bin/storm: import: not found
bin/storm: 34: bin/storm: except: not found
bin/storm: 36: bin/storm: import: not found
bin/storm: 38: bin/storm: Syntax error: "(" unexpected
$
```

**Comment by erikdw** [comment]
hey @echinthaka : how are you trying to run it?  I mean, it works fine for me in both the Docker-based setup that @tnachen created, as well as the vagrant-based setup that @pdread100 created.  

I'd like to help with the issue you are seeing, but it's unclear to me what you are doing exactly.  `bin/storm-mesos nimbus` is the correct way to run it, at least in the setups I mentioned earlier.  And I've never done it in a different setup.  I would try the vagrant setup if I was you (though you should remove all the port forwarding except the master's 8080), and if you can get it working there you can compare-and-contrast with the setup you have which is not working.

**Comment by echinthaka** [comment]
@erikdw I'm trying to run this through the bash shell and I get that error when I do it. Is there a way to share the release you created so that I can try with it too?
Also, do you know, just like `http://downloads.mesosphere.io/storm/storm-mesos-0.9.tgz`, will mesosphere host `0.9.3` release too. I asked this earlier but still didn't see that happening.

**Comment by tnachen** [comment]
@echinthaka we can host the 0.9.3 release but I did a discussion with @erikdw and we think the best solution is to create point releases with github and github allows us to the host binary downloads (and we're within the size limit). I think the next steps for us is to create a 0.9.3 release with github and we can then just point to that instead.

**Comment by echinthaka** [comment]
thats awesome @tnachen . When do you think we will be able to see the release in github?

**Comment by erikdw** [comment]
@echinthaka : I'll see if I can figure out how to do the upload to github myself now that @tnachen has imbued me with commit power for this repo.  Will try that later tonight.

Also, regarding the previous question about how you are running it, I would need more info beyond simpl that you are using a bash shell.  e.g., Are you trying to simply run this on a machine without python installed perhaps?  There are multiple requirements that you need to have installed beforehand.  e.g., there is a dependence on the libmesos.so by the mesos-on-storm framework for the MesosNimbus to interact with the mesos-master.  So even if you were able to get the script to successfully launch the MesosNimbus jar, it might just blow up immediately because of not having libmesos.so in its LD_LIBRARY_PATH.

**Comment by echinthaka** [comment]
@erikdw I use ansible to setup the nimbus node and here is what I do there.

1. Through apt-get I install `python-setuptools`, `python-dev` and `mesos`. I guess with this we get all mesos executables and libraries. 
2. Making sure zookeeper, mesos-slave or mesos-master is not running there
3. Download the storm-mesos release, extract it to `/usr/local/etc/storm`
4. Configure the `storm.yaml` and copy it to the `/usr/local/etc/storm/conf/storm.yaml` 
5. Invoke `/usr/local/etc/storm/bin/storm-mesos nimbus`

**Comment by erikdw** [comment]
@echinthaka : honestly, there is more work needed before we have "real" releases.  Right now the version of the storm-mesos tarball only includes the storm version.  That's wrong, we need to also include the version of the storm-mesos repo that the tarball was built from.  Which version of storm do you *want* to be using?  I can build you a version of the repo with that and point you to it.  But we need a couple more changes before I will be comfortable putting them on the github page as a fully-fledged "release" (e.g., the tarball should have all bundled files owned by root instead of the user that runs bin/build-release.sh).

**Comment by echinthaka** [comment]
@erikdw I like to have  at least `0.9.3` but later the better.

**Comment by erikdw** [comment]
hey @echinthaka : I've been struggling a bit in trying to get the `build-release.sh` script to pop out something reasonable for your set up (i.e., without weird permissions & ownership, and with the ability to start and emit logs).  Have you tried using the vagrant set up and comparing the 0.9.0.1 "official" release to the one you build yourself?

**Comment by echinthaka** [comment]
Yes, that was in the back of my mind. Let me do that while you get time to work on this.
BTW, is there a way I can help you here? If you give me info, I may be able to spend time to help fix this.

**Comment by erikdw** [comment]
Since the apache-storm zip file has odd permissions for its dirs, I'm trying to swap it for the tarball instead.

You said that you use "", but I'm guessing this is being done under sudo, right?

**Comment by echinthaka** [comment]
Yes, running that with sudo

**Comment by echinthaka** [comment]
finally found the reason for this error. It was me trying to run this as a shell command. Note: `sh bin/storm nimbus storm.mesos.MesosNimbus`. I didn't realize I was running a python script. Stupid me. It worked after I fixed it. 

Thanks @erikdw and @tnachen and sorry about the false alarm.

**Comment by erikdw** [comment]
@echinthaka : aha!  Glad you got it working.  So seems building it yourself is ok, and we can wait on improving the versioning before forcing builds up onto github.
