### ISSUE TITLE
nimbus.host value in the case of multiple mesos masters

### ISSUE THREAD

**Issue by salimane** [mesos/storm#72]
When you have multiple mesos masters, which value should be set for the nimbus.host configuration ?
for example, I have  ``mesos.master.url: zk://master1:2181,master2:2181,master3:2181/mesos`` .

When I set ``nimbus.host`` to the hostname on each mesos master running ``storm-nimbus``, I end up with 3 storm framework registered on the mesos ui.

Thanks

**Comment by JessicaLHartog** [comment]
Do you have a typo here? ` mesos.master.url: zk://master1:2181master2:2181,master3:2181/mesos`

It seems at the very least that you're missing a comma.

**Comment by salimane** [comment]
@JessicaLHartog yep it was a typo. 
Thanks

**Comment by erikdw** [comment]
@salimane : we're confused -- are you saying it was a typo in the *question* or a typo in your config?  (because I see that you updated the question).

Furthermore, I'm confused about this statement "each mesos master running `storm-nimbus`"  --> are you saying that you're running 3 copies of `storm-nimbus`?  If so, then that is your problem -- you are indeed running 3 frameworks.  You should only run that command once.

**Comment by salimane** [comment]
@erikdw so even though I have 3 mesos masters, I should only run storm-nimbus on one of the master. So if that master goes down, the storm cluster goes down. I thought we would have some HA by run storm on mesos because mesos already jave HA if you have multiple mesos masters.
Thanks

**Comment by erikdw** [comment]
@salimane : the choice of where to run your MesosNimbus is orthogonal to where you run your mesos-masters.

**Comment by salimane** [comment]
@erikdw ah I see
Thanks

**Comment by erikdw** [comment]
@salimane ^ please see my updates to my comment above.
