### ISSUE TITLE
Ability to set docker user and docker registry in build-release.sh

### ISSUE THREAD

**Issue by DarinJ** [mesos/storm#92]
This should be straight forward using environment variable similar to how MESOS_VERSION and STORM_VERSION were done.  This would enable publishing docker images to person github accounts and/or private registries.

**Comment by erikdw** [comment]
@DarinJ : can you please look at our post-#120 world (specifically the `Makefile` added by #120), and see if it suffices for what you had in mind?  For pushing to our own registry it seems that setting the `DOCKER_REPO` is sufficient, since Docker says you can just [put the registry hostname + port in the repo name](https://blog.docker.com/2013/07/how-to-use-your-own-registry/).   And perhaps that is also sufficient for the "user" you're referring to?  (I'm guessing you were referring to the user for dockerhub.)

**Comment by DarinJ** [comment]
@erikdw yeah I think DOCKER_REPO handles it nicely! Thanks @salimane!
